[FIX] Fix undefined reference to vpStatisticalTestShewhart::CONST_ALL_WECO_ACTIVATED
The solution that has been chosen is to used a vector instead of a C-array