Rename to "npz_save_str()". When adding the bool compress_data parameter, compilation gives:
<>/visp/tutorial/misc/npz/tutorial-npz.cpp: In function ‘int main()’:
<>/visp/tutorial/misc/npz/tutorial-npz.cpp:61:25: error: call of overloaded ‘npz_save(const std::string&, const std::string&, __gnu_cxx::__alloc_traits<std::allocator<char>, char>::value_type*, <brace-enclosed initializer list>, const char [2])’ is ambiguous
   61 |     visp::cnpy::npz_save(npz_filename, identifier, &vec_save_string[0], { vec_save_string.size() }, "w");
      |     ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from <>/visp/tutorial/misc/npz/tutorial-npz.cpp:42:
<>/visp/modules/core/include/visp3/core/vpIoTools.h:297:27: note: candidate: ‘void visp::cnpy::npz_save(const std::string&, std::string, const T*, const std::vector<long unsigned int>&, const std::string&, bool) [with T = char; std::string = std::__cxx11::basic_string<char>]’
  297 | template<typename T> void npz_save(const std::string &zipname, std::string fname, const T *data, const std::vector<size_t> &shape,
      |                           ^~~~~~~~
<>/visp/modules/core/include/visp3/core/vpIoTools.h:190:18: note: candidate: ‘void visp::cnpy::npz_save(const std::string&, const std::string&, const std::string&, const std::string&, bool)’
  190 | VISP_EXPORT void npz_save(const std::string &zipname, const std::string &fname, const std::string &data,
      |                  ^~~~~~~~

<>/visp/tutorial/tracking/model-based/generic/tutorial-mb-generic-tracker-save.cpp: In function ‘int main(int, char**)’:
<>/visp/tutorial/tracking/model-based/generic/tutorial-mb-generic-tracker-save.cpp:115:23: error: call of overloaded ‘npz_save(std::string&, const char [12], __gnu_cxx::__alloc_traits<std::allocator<char>, char>::value_type*, <brace-enclosed initializer list>, const char [2])’ is ambiguous
  115 |   visp::cnpy::npz_save(npz_filename, "camera_name", &vec_camera_name[0], { vec_camera_name.size() }, "w"); // overwrite
      |   ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from <>/visp/tutorial/tracking/model-based/generic/tutorial-mb-generic-tracker-save.cpp:3:
<>/visp/modules/core/include/visp3/core/vpIoTools.h:297:27: note: candidate: ‘void visp::cnpy::npz_save(const std::string&, std::string, const T*, const std::vector<long unsigned int>&, const std::string&, bool) [with T = char; std::string = std::__cxx11::basic_string<char>]’
  297 | template<typename T> void npz_save(const std::string &zipname, std::string fname, const T *data, const std::vector<size_t> &shape,
      |                           ^~~~~~~~
<>/visp/modules/core/include/visp3/core/vpIoTools.h:190:18: note: candidate: ‘void visp::cnpy::npz_save(const std::string&, const std::string&, const std::string&, const std::string&, bool)’
  190 | VISP_EXPORT void npz_save(const std::string &zipname, const std::string &fname, const std::string &data,
      |                  ^~~~~~~~

Add support for ZIP64 compression when using npz_save(), see: https://github.com/rogersce/cnpy/pull/103
See NumPy doc: https://numpy.org/doc/stable/reference/generated/numpy.savez_compressed.html