Add missing nlohmann_json dependency Issue detected on windows cdash ci modules\tracker\klt\include\visp3/klt/vpKltOpencv.h(57,10): fatal  error C1083: Impossible d'ouvrir le fichier include : 'nlohmann/json.hpp' : No such file or directory [C:\...\modules\klt\visp_klt.vcxproj]