Attempt to add protobuf dependency installation on macos-11
Since the Qt5 build seems failing because protobuf is not found
/tmp/qt-20231104-5483-1fey0cz/qt-everywhere-src-6.5.2/qtgrpc/src/tools/qtprotoccommon/generatorbase.cpp:8:10: fatal error: 'google/protobuf/stubs/logging.h' file not found