Set min libapriltag system version to 3.3.0
Version 3.2.0 available on ubuntu 22.04 (libapriltag-dev) is too old
It doesn't expose workerpool_create() and utime_now()
Introducing these functions in vpApriltagDetection.cpp would be possible, but too havy to maintain
[100%] Linking CXX executable catchArUco
/usr/bin/ld: ../../lib/libvisp_detection.so.3.7.1: undefined reference to `workerpool_create'
/usr/bin/ld: ../../lib/libvisp_detection.so.3.7.1: undefined reference to `utime_now'
collect2: error: ld returned 1 exit status