Disable Vicon SDK support when c++98 standard is used. Close #1930
Vicon SDK requires at least c++11 standard.
There is the build issue when c++98 is set and VISP_HAVE_VICON is defined
In file included from visp/modules/sensor/src/mocap/vpMocapVicon.cpp:44:
visp-ws/3rdparty/vicon/20230413_145507h/Release/Linux64/DataStreamClient.h:43:10: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
   43 |     std::shared_ptr< std::vector< unsigned char > > m_Data;
      |          ^~~~~~~~~~