Fixed error where INT32 was defined by jpeg headers before windows headers : c:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\basetsd.h(78): error C2371: 'INT32' : redefinition; different basic types c:\libraries\jpeg-8c\jmorecfg.h(165) : see declaration of 'INT32'