Changes to be able to detect ant in defaut path This change was introduced for Ubuntu 20.04 where ant was found in /bin/ant but produces and error when running:
$ /bin/ant -version
/bin/ant: 1: cd: can't cd to /bin/../share/ant/bin/..
Error: Could not find or load main class org.apache.tools.ant.launch.Launcher
Caused by: java.lang.ClassNotFoundException: org.apache.tools.ant.launch.Launcher

This commit allows to detect ant in /usr/bin/ant
$  /usr/bin/ant -version
Apache Ant(TM) version 1.10.7 compiled on October 24 2019