Fix pr335 (#336)
* warning C4838: conversion from 'double' to 'float' requires a narrowing conversion
* Fix error: ‘INT32_MAX’ was not declared in this scope
* Fix warning: comparing floating point with == or != is unsafe
* Fix warning: comparing floating point with == or != is unsafe
* Fix warning: this decimal constant is unsigned only in ISO C90

* Fix warning: assuming signed overflow does not occur when simplifying conditional to constant

* Fix warning: comparison of unsigned expression >= 0 is always true

* Fix type of source file from extension

* Turn warning off in clapack 3rd party