Fix doc parsing when generating python stubs by removing BEGIN_VISP_NAMESPACE and END_VISP_NAMESPACE macros. Closes #1856. Modifying doc_parser.py around line 350 with
if method_def.name == cls_name or ret_type != '':
  signature_str = f'{ret_type} {cls_name}::{method_def.name}({",".join(param_types)}) {{}}'
  print(f'---------- DEBUG Parsing signature for doc matching: {signature_str} --')
  method = parse_string(signature_str).namespace.method_impls[0]

shows that the script hangs parsing the following signature_str string:

---------- DEBUG Parsing signature for doc matching: BEGIN_VISP_NAMESPACE vpHSV < double > & vpHSV::buildFrom(constvpRGBa &) {} --

followed by the issues:

Traceback (most recent call last):
  File "/Users/fspindle/miniforge3/envs/visp-conda-ws/lib/python3.12/site-packages/cxxheaderparser/parser.py", line 351, in parse
    self._parse_declarations(tok, doxygen)
  File "/Users/fspindle/miniforge3/envs/visp-conda-ws/lib/python3.12/site-packages/cxxheaderparser/parser.py", line 2683, in _parse_declarations
    tok = self._next_token_must_be(",", ";")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fspindle/miniforge3/envs/visp-conda-ws/lib/python3.12/site-packages/cxxheaderparser/parser.py", line 170, in _next_token_must_be
    raise self._parse_error(tok, "' or '".join(tokenTypes))
cxxheaderparser.errors.CxxParseError: unexpected '&', expected ',' or ';'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/fspindle/miniforge3/envs/visp-conda-ws/lib/python3.12/site-packages/visp_python_bindgen/generator.py", line 179, in <module>
    main()
  File "/Users/fspindle/miniforge3/envs/visp-conda-ws/lib/python3.12/site-packages/visp_python_bindgen/generator.py", line 176, in main
    generate_module(generation_path_src, config_path)
  File "/Users/fspindle/miniforge3/envs/visp-conda-ws/lib/python3.12/site-packages/visp_python_bindgen/generator.py", line 137, in generate_module
    submodule.generate()
  File "/Users/fspindle/miniforge3/envs/visp-conda-ws/lib/python3.12/site-packages/visp_python_bindgen/submodule.py", line 145, in generate
    header.generate_binding_code(module_bindings)
  File "/Users/fspindle/miniforge3/envs/visp-conda-ws/lib/python3.12/site-packages/visp_python_bindgen/header.py", line 183, in generate_binding_code
    self.parse_data(bindings_container)
  File "/Users/fspindle/miniforge3/envs/visp-conda-ws/lib/python3.12/site-packages/visp_python_bindgen/header.py", line 202, in parse_data
    self.documentation_holder = DocumentationHolder(self.documentation_holder_path, self.environment.mapping)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fspindle/miniforge3/envs/visp-conda-ws/lib/python3.12/site-packages/visp_python_bindgen/doc_parser.py", line 353, in __init__
    method = parse_string(signature_str).namespace.method_impls[0]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fspindle/miniforge3/envs/visp-conda-ws/lib/python3.12/site-packages/cxxheaderparser/simple.py", line 345, in parse_string
    parser.parse()
  File "/Users/fspindle/miniforge3/envs/visp-conda-ws/lib/python3.12/site-packages/cxxheaderparser/parser.py", line 369, in parse
    raise CxxParseError(msg) from e
cxxheaderparser.errors.CxxParseError: <str>:1: parse error evaluating '&': unexpected '&', expected ',' or ';'
make[3]: *** [modules/python/CMakeFiles/visp_python_bindings_generator_run.dir/build.make:146: modules/python/bindings/src/main.cpp] Error 1
make[2]: *** [CMakeFiles/Makefile2:33483: modules/python/CMakeFiles/visp_python_bindings_generator_run.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:33541: modules/python/CMakeFiles/visp_python_bindings.dir/rule] Error 2
make: *** [Makefile:8330: visp_python_bindings] Error 2