Disable build on armv7 arch that produces the following issue while the changes introduced in previous commit make the other arch working
Build container
  GitHub token provided, caching to ghcr.io/lagadic/visp/run-on-arch-lagadic-visp-other-architectures-isolated-none-none
  WARNING! Your password will be stored unencrypted in /home/runner/.docker/config.json.
  Configure a credential helper to remove this warning. See
  https://docs.docker.com/engine/reference/commandline/login/#credentials-store

  Login Succeeded
  Error response from daemon: manifest unknown
  #0 building with "default" instance using docker driver

  #1 [internal] load build definition from Dockerfile.none.none
  #1 transferring dockerfile: 221B done
  #1 DONE 0.0s

  #2 [auth] library/ubuntu22.04:pull token for registry-1.docker.io
  #2 DONE 0.0s

  #3 [internal] load metadata for docker.io/library/ubuntu22.04:latest
  #3 ERROR: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
  ------
   > [internal] load metadata for docker.io/library/ubuntu22.04:latest:
  ------
  Dockerfile.none.none:1
  --------------------
     1 | >>> FROM --platform=linux/armv7 ubuntu22.04
     2 |     COPY ./run-on-arch-install.sh /root/run-on-arch-install.sh
     3 |     RUN chmod +x /root/run-on-arch-install.sh && /root/run-on-arch-install.sh
  --------------------
  ERROR: failed to solve: ubuntu22.04: failed to resolve source metadata for docker.io/library/ubuntu22.04:latest: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
  Error: The process '/home/runner/work/_actions/uraimo/run-on-arch-action/v2/src/run-on-arch.sh' failed with exit code 1