Add missing vpPoint.h header include
Produced the following error during python bindings generation

miniforge3/envs/visp-conda-ws/include/pybind11/pybind11.h:136:13: error: return type 'class vpPoint' is incomplete

  136 |             [f](Class *c, Arg... args) -> Return { return (c->*f)(std::forward<Arg>(args)...); },

miniforge3/envs/visp-conda-ws/include/pybind11/pybind11.h:136:66: error: invalid use of incomplete type 'class vpPoint'